In [2]:
!pip install numpy


In [3]:
import numpy as np

# CREACIÓN E INDEXACIÓN

#### 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5

In [7]:
array1 = np.random.randint (10, 99, 50, int)
array1

array([75, 37, 72, 92, 82, 78, 21, 82, 59, 58, 78, 25, 68, 57, 97, 77, 76,
       42, 88, 79, 50, 63, 69, 55, 63, 10, 54, 59, 41, 46, 37, 98, 51, 94,
       70, 91, 15, 16, 25, 97, 61, 53, 88, 63, 65, 33, 95, 94, 35, 50])

In [12]:
array1[5::5]

array([78, 78, 77, 50, 10, 37, 91, 61, 33])

#### 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares

In [40]:
array2 = np.random.randint (1, 21, 30, int)
array2

array([12,  7, 10, 15, 16, 12,  3,  4,  4, 13, 20, 11, 11,  7,  3, 19,  1,
       20,  6, 16, 14, 16,  6,  2,  7,  2, 14,  8,  4, 11])

In [21]:
array2[1::2]

array([ 4, 12, 20, 14, 16,  5, 15, 17,  5,  1, 10, 20,  3,  4,  8])

#### 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales

In [50]:
array_randint_bi = np.random(0, 50, (2,3), float)

SyntaxError: invalid syntax (2210707315.py, line 1)

In [42]:
array3 = np.random.rand(1,21 (4,6) t)
array3



TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
import numpy as np

# Crear un array 2D de forma (4, 6) con números aleatorios decimales
arr = np.random.uniform(low=-100.0, high=100.0, size=(4, 6))

# Acceder a la última fila de la matriz
last_row = arr[-1]

# Redondear los decimales a 2 decimales
last_row_rounded = np.round(last_row, 2)

print(last_row_rounded)

In [44]:
array3 = np.arange(1,21,(4,6))
array3

TypeError: unsupported operand type(s) for /: 'int' and 'tuple'

In [31]:
np.round(array3[-1,],2) 

array([0.83, 0.98, 0.91, 0.31, 0.19, 0.41])

#### 4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales

In [32]:
array4 = np.random.rand(6,4)
array4

array([[0.75347854, 0.29405312, 0.73989917, 0.83199575],
       [0.61588224, 0.53399207, 0.8453044 , 0.80175398],
       [0.77420038, 0.59558416, 0.47563843, 0.27117434],
       [0.4792709 , 0.55968784, 0.06347147, 0.62859642],
       [0.73648678, 0.60903255, 0.15581779, 0.43327703],
       [0.0287776 , 0.34137127, 0.25389488, 0.78934105]])

In [36]:
np.round(array4[:,1],2) 

array([0.29, 0.53, 0.6 , 0.56, 0.61, 0.34])

#### 5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos (Miriam)

In [59]:
array5 = np.random.randint(-50, 50, 30)
array5

array([ 43, -30,  28,  17, -26,   9,  10,  11,  -7, -24,  26, -29,  39,
        -9,  33, -18,  49, -40, -30, -34,  37, -16, -14, -50, -33, -17,
        44, -10, -18,  31])

In [61]:
resultado5 = np.where(array5 < 0, True, False)

resultado5

array([False,  True, False, False,  True, False, False, False,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True, False])

#### 6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos? (Elena)


#### 7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4 (Miriam)

#### BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0 (Elena)

# Reshape y Transpose

#### 1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio (Miriam)

#### 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D (Elena)

#### 3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D (Miriam)

#### 4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3) (Elena)

#### 5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4) (Miriam)

# Teóricas

#### 6. ¿Qué diferencia existe entre el reshape y el transpose? (Miriam)

#### 7. ¿Y entre el transpose y el swapaxes?  (Elena)

# Funciones y estadística

#### 1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal. (Miriam)

#### 2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".