In [5]:
!pip install numpy


In [6]:
import numpy as np

# CREACIÓN E INDEXACIÓN

#### 1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5

In [7]:
array1 = np.random.randint (10, 99, 50, int)
array1

array([47, 73, 14, 90, 22, 12, 68, 31, 12, 70, 12, 70, 32, 49, 53, 48, 97,
       38, 10, 33, 71, 69, 45, 77, 22, 87, 65, 20, 18, 33, 84, 30, 23, 60,
       19, 90, 90, 87, 16, 53, 46, 27, 78, 47, 25, 25, 65, 48, 80, 65])

In [8]:
array1[5::5]

array([12, 12, 48, 71, 87, 84, 90, 46, 25])

#### 2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares

In [9]:
array2 = np.random.randint (1, 21, 30, int)
array2

array([12,  7,  6, 10,  1,  9,  2,  1,  3,  6, 10,  3,  8, 19, 12, 10,  3,
       16, 12,  9,  6, 15, 20, 18,  1,  7,  2, 19, 16,  4])

In [10]:
array2[1::2]

array([ 7, 10,  9,  1,  6,  3, 19, 10, 16,  9, 15, 18,  7, 19,  4])

#### 3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales

In [16]:
# Puesto que no hay un código directo para crear un array de nros aleatorios decimales, lo podemos hacer de 2 formas: 

# Opción 1: Creamos 2 matrices: una con números enteros y otra con decimales y las sumamos -
enteros = np.random.randint(0, 20, (4,6))
enteros

array([[15,  9, 15, 17, 11, 10],
       [14,  8,  1, 16,  0,  9],
       [16, 11, 11, 12, 11,  7],
       [17,  9,  8, 15, 17, 13]])

In [18]:
decimales = np.random.rand(4,6)
decimales

array([[0.74282282, 0.12787129, 0.75147414, 0.56716659, 0.75708011,
        0.6707252 ],
       [0.60032362, 0.40043888, 0.99537105, 0.71638462, 0.33814663,
        0.28010145],
       [0.95217525, 0.02069376, 0.62528619, 0.39652759, 0.82730848,
        0.07706993],
       [0.49322214, 0.92367626, 0.42124698, 0.16462513, 0.2754593 ,
        0.56422837]])

In [26]:
array3_opcion1=np.add(enteros,decimales)
np.round(array3_opcion1,2)

array([[15.74,  9.13, 15.75, 17.57, 11.76, 10.67],
       [14.6 ,  8.4 ,  2.  , 16.72,  0.34,  9.28],
       [16.95, 11.02, 11.63, 12.4 , 11.83,  7.08],
       [17.49,  9.92,  8.42, 15.16, 17.28, 13.56]])

In [ ]:
# Opción 2: Le sumamos 5 a aca uno de los valores de la matriz de decimales

In [23]:
array3_opcion2 = decimales + 5

In [25]:
np.round(array3_opcion2,2)

array([[5.74, 5.13, 5.75, 5.57, 5.76, 5.67],
       [5.6 , 5.4 , 6.  , 5.72, 5.34, 5.28],
       [5.95, 5.02, 5.63, 5.4 , 5.83, 5.08],
       [5.49, 5.92, 5.42, 5.16, 5.28, 5.56]])

#### 4. Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales

In [ ]:
array4 = np.random.rand(6,4)
array4

array([[0.75347854, 0.29405312, 0.73989917, 0.83199575],
       [0.61588224, 0.53399207, 0.8453044 , 0.80175398],
       [0.77420038, 0.59558416, 0.47563843, 0.27117434],
       [0.4792709 , 0.55968784, 0.06347147, 0.62859642],
       [0.73648678, 0.60903255, 0.15581779, 0.43327703],
       [0.0287776 , 0.34137127, 0.25389488, 0.78934105]])

In [ ]:
np.round(array4[:,1],2) 

array([0.29, 0.53, 0.6 , 0.56, 0.61, 0.34])

#### 5. Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos (Miriam)

In [ ]:
array5 = np.random.randint(-50, 50, 30)
array5

array([ 43, -30,  28,  17, -26,   9,  10,  11,  -7, -24,  26, -29,  39,
        -9,  33, -18,  49, -40, -30, -34,  37, -16, -14, -50, -33, -17,
        44, -10, -18,  31])

In [ ]:
resultado5 = np.where(array5 < 0, True, False)

resultado5

array([False,  True, False, False,  True, False, False, False,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True,  True, False,
        True,  True, False])

#### 6. Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos? (Elena)


In [29]:
array6 = np.round(np.random.rand(10),2)
array6

array([0.89, 0.51, 0.98, 0.71, 0.28, 0.27, 0.64, 0.49, 0.52, 0.69])

In [32]:
np.where(array6>0.5) #Lo que nos devuelve es un array de nros, en el que cada nro es la posición del valor en el array 6 donde se cumple la condición de que el valor sea superior a 0.5

(array([0, 1, 2, 3, 6, 8, 9]),)

#### 7. Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4 (Miriam)

#### BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0 (Elena)

In [106]:
array8 = np.random.randint(0, 101, (2,3,5))
array8

array([[[ 19,  42,  17,  26,  75],
        [ 97,  16,  41,  42,  15],
        [ 54,  74,  26,  47,  20]],

       [[ 28,  59,  45,   3, 100],
        [ 66,  52,   4,  76,  50],
        [ 51,  10,  17,  99,  76]]])

In [107]:
condición =array8[:,:,3]  #esta sería la condición - me coge los valores que están en las posiciones que son múltiples de 3, es decir, odos los que están en la columna 3
condición

array([[26, 42, 47],
       [ 3, 76, 99]])

In [109]:
np.where(array8[condición],0, False)  ### NO ME SALE

IndexError: index 26 is out of bounds for axis 0 with size 2

In [37]:
# NOTA: Esto es para los valores que son múltiples de 3 PERO NO LAS POSICIONES
np.where(array8%3==0, 0,array8) #Para que me remplace sólo los q son múltiples de 3 pero que deje los otros valores, pongo "array8" en la opción de Falso

array([[[56,  0,  0, 80, 83],
        [31, 38, 37, 35,  2],
        [ 0, 77,  8, 70,  0]],

       [[86,  0,  0, 35, 25],
        [ 0,  0, 49,  0, 68],
        [76,  0, 52, 10, 65]]])

# Reshape y Transpose

#### 1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio (Miriam)

#### 2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D (Elena)

In [54]:
array_2 = np.random.randint(1,60, (3,4,5))
array_2

array([[[17, 22,  5, 30, 26],
        [13, 57, 32, 13, 29],
        [40,  9, 26, 34, 50],
        [50, 10, 16,  5, 49]],

       [[54, 39,  2, 36, 53],
        [ 4, 28, 43, 20, 12],
        [ 7, 59, 48,  6, 30],
        [10, 23, 11, 31, 54]],

       [[35, 17, 25, 44, 36],
        [37, 54, 48, 24,  4],
        [55, 26, 21, 13, 38],
        [59, 45, 35, 49,  6]]])

In [57]:
reshaped_2 = np.reshape(array_2, (12,5))
reshaped_2

array([[17, 22,  5, 30, 26],
       [13, 57, 32, 13, 29],
       [40,  9, 26, 34, 50],
       [50, 10, 16,  5, 49],
       [54, 39,  2, 36, 53],
       [ 4, 28, 43, 20, 12],
       [ 7, 59, 48,  6, 30],
       [10, 23, 11, 31, 54],
       [35, 17, 25, 44, 36],
       [37, 54, 48, 24,  4],
       [55, 26, 21, 13, 38],
       [59, 45, 35, 49,  6]])

#### 3. Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D (Miriam)

#### 4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3) (Elena)

In [58]:
array_2 ##dimensión: 3, 4, 5

array([[[17, 22,  5, 30, 26],
        [13, 57, 32, 13, 29],
        [40,  9, 26, 34, 50],
        [50, 10, 16,  5, 49]],

       [[54, 39,  2, 36, 53],
        [ 4, 28, 43, 20, 12],
        [ 7, 59, 48,  6, 30],
        [10, 23, 11, 31, 54]],

       [[35, 17, 25, 44, 36],
        [37, 54, 48, 24,  4],
        [55, 26, 21, 13, 38],
        [59, 45, 35, 49,  6]]])

In [59]:
np.transpose(array_2) #Devuelve 5, 4, 3

array([[[17, 54, 35],
        [13,  4, 37],
        [40,  7, 55],
        [50, 10, 59]],

       [[22, 39, 17],
        [57, 28, 54],
        [ 9, 59, 26],
        [10, 23, 45]],

       [[ 5,  2, 25],
        [32, 43, 48],
        [26, 48, 21],
        [16, 11, 35]],

       [[30, 36, 44],
        [13, 20, 24],
        [34,  6, 13],
        [ 5, 31, 49]],

       [[26, 53, 36],
        [29, 12,  4],
        [50, 30, 38],
        [49, 54,  6]]])

#### 5. Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4) (Miriam)

# Teóricas

#### 6. ¿Qué diferencia existe entre el reshape y el transpose? (Miriam)

#### 7. ¿Y entre el transpose y el swapaxes?  (Elena)

In [66]:
#Swapaxes permite intercambiar los ejes de un array. Y tranpsose permite cambiar el orden de los ejes como se quiera

# Funciones y estadística

#### 1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal. (Miriam)

#### 2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones
- Si el valor del array es igual que la media, se reemplaza por "A".
- Si el valor del array es mayor que la media, se reemplaza por "B".
- Si el valor del array es menor que la media, se reemplaza por "C".
- Si el valor es igual que el máximo, se reemplaza por "D".
- Si el valor es igual que el mínimo, se reemplaza por "E".

In [72]:
array_ultimo = np.empty((2,3,5))
array_ultimo

array([[[4.67977167e-310, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000, 6.89882052e-310],
        [5.02034658e+175, 1.05183075e-046, 5.88172232e-062,
         1.84638478e-076, 2.64268614e+180],
        [1.04806398e-042, 2.16385130e+190, 1.94918964e-153,
         4.90838520e+252, 1.30304358e-142]],

       [[1.06396443e+224, 1.46901661e+179, 1.04917933e-153,
         9.08366793e+223, 1.05183075e-046],
        [5.88172232e-062, 1.84638478e-076, 2.64268614e+180,
         1.04917696e-153, 1.94918966e-153],
        [9.72158982e-072, 1.48330801e-071, 5.05804714e-038,
         2.59027896e-144, 7.79952704e-143]]])

In [87]:
media = np.mean(array_ultimo)
media

1.6361284003330696e+251

In [84]:
#Si el valor del array es igual que la media, se reemplaza por "A"
np.where(array_ultimo == media, "A", array_ultimo)

array([[['4.6797716651793e-310', '0.0', '0.0', '0.0',
         '6.8988205160072e-310'],
        ['5.020346578198683e+175', '1.0518307477218933e-46',
         '5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180'],
        ['1.0480639756145421e-42', '2.163851297410559e+190',
         '1.9491896422031877e-153', '4.9083852009992084e+252',
         '1.3030435793939972e-142']],

       [['1.063964430317807e+224', '1.4690166124022477e+179',
         '1.0491793330286782e-153', '9.083667925815433e+223',
         '1.0518307477218933e-46'],
        ['5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180', '1.049176963488146e-153',
         '1.949189659567389e-153'],
        ['9.721589820707176e-72', '1.4833080050797415e-71',
         '5.058047136452858e-38', '2.5902789599218684e-144',
         '7.799527044147088e-143']]], dtype='<U32')

In [86]:
# Si el valor del array es mayor que la media, se reemplaza por "B"
np.where(array_ultimo <  media, "B", array_ultimo)

array([[['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'B', '4.9083852009992084e+252', 'B']],

       [['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B']]], dtype='<U32')

In [85]:
# Si el valor del array es menor que la media, se reemplaza por "C"
np.where(array_ultimo > media, "C", array_ultimo)

array([[['4.6797716651793e-310', '0.0', '0.0', '0.0',
         '6.8988205160072e-310'],
        ['5.020346578198683e+175', '1.0518307477218933e-46',
         '5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180'],
        ['1.0480639756145421e-42', '2.163851297410559e+190',
         '1.9491896422031877e-153', 'C', '1.3030435793939972e-142']],

       [['1.063964430317807e+224', '1.4690166124022477e+179',
         '1.0491793330286782e-153', '9.083667925815433e+223',
         '1.0518307477218933e-46'],
        ['5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180', '1.049176963488146e-153',
         '1.949189659567389e-153'],
        ['9.721589820707176e-72', '1.4833080050797415e-71',
         '5.058047136452858e-38', '2.5902789599218684e-144',
         '7.799527044147088e-143']]], dtype='<U32')

In [91]:
# Si el valor es igual que el máximo, se reemplaza por "D"
maximo = np.max(array_ultimo)
maximo

4.9083852009992084e+252

In [90]:
np.where(array_ultimo == maximo, "D", array_ultimo)

array([[['4.6797716651793e-310', '0.0', '0.0', '0.0',
         '6.8988205160072e-310'],
        ['5.020346578198683e+175', '1.0518307477218933e-46',
         '5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180'],
        ['1.0480639756145421e-42', '2.163851297410559e+190',
         '1.9491896422031877e-153', 'D', '1.3030435793939972e-142']],

       [['1.063964430317807e+224', '1.4690166124022477e+179',
         '1.0491793330286782e-153', '9.083667925815433e+223',
         '1.0518307477218933e-46'],
        ['5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180', '1.049176963488146e-153',
         '1.949189659567389e-153'],
        ['9.721589820707176e-72', '1.4833080050797415e-71',
         '5.058047136452858e-38', '2.5902789599218684e-144',
         '7.799527044147088e-143']]], dtype='<U32')

In [93]:
#Si el valor es igual que el mínimo, se reemplaza por "E"

minimo= np.min(array_ultimo)
minimo

0.0

In [94]:
np.where(array_ultimo == minimo, "E", array_ultimo)

array([[['4.6797716651793e-310', 'E', 'E', 'E', '6.8988205160072e-310'],
        ['5.020346578198683e+175', '1.0518307477218933e-46',
         '5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180'],
        ['1.0480639756145421e-42', '2.163851297410559e+190',
         '1.9491896422031877e-153', '4.9083852009992084e+252',
         '1.3030435793939972e-142']],

       [['1.063964430317807e+224', '1.4690166124022477e+179',
         '1.0491793330286782e-153', '9.083667925815433e+223',
         '1.0518307477218933e-46'],
        ['5.881722320455348e-62', '1.8463847793898974e-76',
         '2.6426861409021448e+180', '1.049176963488146e-153',
         '1.949189659567389e-153'],
        ['9.721589820707176e-72', '1.4833080050797415e-71',
         '5.058047136452858e-38', '2.5902789599218684e-144',
         '7.799527044147088e-143']]], dtype='<U32')